### ISSUE TITLE
Getting it running?

### ISSUE THREAD

**Issue by kmarekspartz** [nirgn975/Elmctron#3]
Likely a config issue on my end...

I did `npm install` and that worked. No gulp: `gulp: command not found`. `npm install gulp`. No gulp. `npm install gulp -g`, and then gulp was found, but: 

```
(node:90604) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
[10:35:45] Using gulpfile ~/src/Elmctron/gulpfile.js
[10:35:45] Starting 'elm-init'...
[10:35:45] Starting 'sass'...
[10:35:45] Starting 'watch'...
[10:35:45] Finished 'watch' after 12 ms
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: spawn elm-make ENOENT
    at exports._errnoException (util.js:1007:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:182:32)
    at onErrorNT (internal/child_process.js:348:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

**Comment by nirgn975** [comment]
@zeckalpha It looks like a problem with `elm-make`. Try to install it globally, manually,  by run `npm install -g elm`. Please, keep me posted  (:

**Comment by kmarekspartz** [comment]
That worked. I wonder if the local npm path wasn't getting picked up for some reason. I'll look into that a bit, and update the README and send you a PR.

–
Kyle Marek-Spartz
